site_name: Kubernetes
site_description: Structured educational documentation and cluster operations
site_author: valvalov
repo_url: https://github.com/valvalov/kubernetes
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: indigo
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.highlight
    - search.suggest

nav:
  - Home: index.md
  - Install:
      - Common: install/common/index.md
      - Common Steps:
          - Prerequisites: install/common/prerequisites.md
          - Containerd Setup: install/common/install-containerd.md
          - Repositories: install/common/add-repositories.md
          - Kubernetes Tools: install/common/install-kube-tools.md
      - With kubeadm: install/kubeadm/index.md
      - Airgapped: install/airgap/index.md
      - MicroK8s: install/microk8s/index.md
      - Troubleshooting: install/troubleshooting/index.md
